---
title: "RTRS_Minutes_12-3-20"
author: "Joseph Rickert"
date: "12/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Tables fro Regulatory Submissions Working Group

Minutes for 12-3-20 meeting prepared by Joseph Rickert

## Attendees

* Joseph Rickert
* Adrian Waddell
* Andy Nichole
* Arthur Allignol
* Bob Engle
* Daniel Sjoberg
* Himanshu Pandya
* Mark Baillie
* Martin Brown
* Mike Stackhouse
* Ning Leng
* Tadeusz Lewandowski
* Pierre Wallet
* Yilong Zhang
* Bryant Chen
* Keaven Anderson
* Kevin Bolger
* Søren Klim

Joseph Rickert opened the meeting by noting that the minutes from previous meetings along with a draft requirements document are available on the GitHub repository. 

Mention of the requirements document initiated some discussion about separating table specific requirements from document level requirements on pagination, alignment etc. Some thought that the content of a table should be separated from the layout. It was noted that individual company practices vary widely about what goes into tables. Some companies put foot notes in the footers, while others include footnotes within the body of the table. Søren Klim noted that it is common for different groups within a company to be responsible for the production of a table. Biostatisticians may produce the content for a table, but they do not own the table. 

These considerations led to a the discussion of workflows. It was noted that company specific workflows for generating documents and tables differ in many aspects, but invariably include medical writers who must copy and paste information into tables and hand edit tables. Examples given include manually deleting "%" signs after multiple lines of numbers in favor of inserting the % symbol in the table header, or removing "0" from SAS generated tables. 

Another commonality of workflows is the prevalence of RTF and Microsoft Word documents. Among the reasons offered that make it difficult to avoid MS Word are features such as ability to track changes. 

There was general agreement that it would be good to work towards a standard workflow. However, there is no clear path on where to begin. Ning Leng remarked that Roche is committed to R, but will likely be producing hybrid submissions for some time to come. Keaven Anderson raised the issue of what is the proper level of abstraction to consider. With regard to this, someone raised the issue of working with "Listings" which are tables with special constraints.

Some participants favored "work around" solutions in the short term. Mike Stackhouse expressed the opinion that it is important to make R work for existing processes. Yilong Zhang mentioned, for example, making a table in R that looks like it was generated by SAS, and Bob Engle going from R to RTF could be part of a continuous workflow.

Others noted that it is important to build up a tool kit while doing exploratory work that will eventually useful for submissions.

The meeting closed with a discussion of open source R packages that are relevant to table making. Yilong Zhang suggested that it would be helpful to consider creating a Task View for Table Generation. The idea was received very positively by those in attendance.

The next meeting was set for 9:00 AM Pacific Time on Thursday January 7, 2021.

Joseph Rickert encouraged everyone to use the issues feature of the GitHub repo to enter an ideas or suggestion they may have and called the meeting to a close.
