---
output: html_document
editor_options: 
  chunk_output_type: console
---

## Disposition

### rtables

```{r, comment=NA}
resetSession()

library(dplyr)
library(magrittr)
library(rtables)

data("cadsl", package = "random.cdisc.data")
adsl <- cadsl |>
  select(USUBJID, TRT01A, EOSSTT, DCSREAS)

lyt <- basic_table() |>
  split_cols_by("TRT01A") |>
  add_colcounts() |>
  split_rows_by("EOSSTT") |>
  split_rows_by("DCSREAS") |>
  summarize_row_groups()

build_table(lyt, adsl)

```
### gt

```{r}
resetSession()

library(tidyverse)
library(gt)

gt_adsl <- cadsl |> 
  dplyr::group_by(TRT01A) |> 
  dplyr::mutate(n_total = dplyr::n()) |> 
  dplyr::ungroup()

header_n <- gt_adsl |> 
  dplyr::group_by(TRT01A) |> 
  dplyr::summarize(trt = sprintf("%s  \nN=%i (100%%)", unique(TRT01A), dplyr::n()),
                   .groups = "drop") |> 
  pull(trt) |> 
  as.list()

names(header_n) <- paste0("n_", levels(gt_adsl$TRT01A))
  
gt_sum <- gt_adsl |> 
  dplyr::mutate(
    DCSREAS = dplyr::case_when(EOSSTT %in% c("COMPLETED", "ONGOING") ~ as.character(EOSSTT),
                               is.na(DTHCAUS) & EOSSTT == "DISCONTINUED" ~ as.character(DCSREAS),
                               TRUE ~ paste(DCSREAS, DTHCAUS, sep = "_"))) |> 
  dplyr::group_by(TRT01A, EOSSTT, DCSREAS) |> 
  dplyr::summarize(
    n = dplyr::n(),
    pct = dplyr::n()/min(n_total),
    .groups = "drop"
    ) |> 
  tidyr::pivot_wider(id_cols = c(EOSSTT, DCSREAS), names_from = TRT01A, values_from = c(n, pct))

dth_lbl <- gt_sum |> 
  dplyr::slice(1) |> 
  dplyr::mutate(
    across(where(is.numeric), ~NA_real_),
           EOSSTT = "DISCONTINUED",
           DCSREAS = "DEATH"
  )
  
gt_disp <- dplyr::bind_rows(gt_sum, dth_lbl) |> 
  dplyr::mutate(
    EOSSTT = factor(EOSSTT,
                    levels = c("COMPLETED", "ONGOING", "DISCONTINUED"),
                    labels = c("Completed", "Ongoing", "Discontinued")),
    DCSREAS = factor(DCSREAS,
                     levels = c("COMPLETED", "ONGOING", "ADVERSE EVENT", "DEATH" ,"DEATH_ADVERSE EVENT", "DEATH_DISEASE PROGRESSION", "DEATH_LOST TO FOLLOW UP", "DEATH_MISSING", "DEATH_Post-study reporting of death", "DEATH_SUICIDE", "DEATH_UNKNOWN", "LACK OF EFFICACY", "PHYSICIAN DECISION", "PROTOCOL VIOLATION", "WITHDRAWAL BY PARENT/GUARDIAN", "WITHDRAWAL BY SUBJECT"),
                     labels = c("Completed", "Ongoing", "Adverse Event", "Death", "Adverse Event ", "Disease Progression", "Lost to Follow Up", "Missing", "Post-Study Reporting of Death", "Suicide", "Unknown", "Lack of Efficacy", "Physician Decision", "Protocol Violation", "Withdrawal by Parent/ Guardian", "Withdrawal by Subject")) 
    ) |> 
  dplyr::arrange(EOSSTT, DCSREAS)


gt_disp |> 
  gt(rowname_col = "DCSREAS") |> 
  tab_row_group(
    label = "Discontinued",
    rows = EOSSTT == "Discontinued"
  ) |> 
  row_group_order(
    groups = c(NA, "Discontinued") 
  ) |> 
  cols_hide(EOSSTT) |> 
  fmt_integer(
    columns = starts_with("n_")
  ) |> 
  fmt_percent(
    columns = starts_with("pct_"),
    decimals = 1
  ) |> 
  sub_missing(
    rows = DCSREAS == "Death",
    missing_text = ""
  ) |> 
  cols_merge_n_pct(col_n = "n_A: Drug X", col_pct = "pct_A: Drug X") |> 
  cols_merge_n_pct(col_n = "n_B: Placebo", col_pct = "pct_B: Placebo") |> 
  cols_merge_n_pct(col_n = "n_C: Combination", col_pct = "pct_C: Combination") |> 
    sub_missing(
    rows = DCSREAS != "Death",
    missing_text = 0
  ) |> 
  cols_align(
    align = "center",
    columns = everything()
  ) |> 
  cols_align(
    align = "left",
    columns = stub()
  ) |> 
  tab_stub_indent(
    rows = 3:16,
    indent = 2
  ) |>
  tab_stub_indent(
    rows = 5:11,
    indent = 5
  ) |> 
  cols_label(
    `n_A: Drug X` = md(header_n[[1]]),
    `n_B: Placebo` = md(header_n[[2]]),
    `n_C: Combination` = md(header_n[[3]])
  ) |> 
  cols_width(
    1 ~ px(500)
  )
```


### flextable

```{r}
resetSession()

library(survival)
library(tidyverse)
library(flextable)
library(glue)

adsl <- cadsl |>
  select(USUBJID, TRT01A, EOSSTT, DCSREAS)

labels <- tools::toTitleCase(tolower(levels(adsl$DCSREAS)))
names(labels) <- levels(adsl$DCSREAS)

# data parts calculations
part_header <- adsl |> count(TRT01A, name = "n_part")

part_completed <- adsl |> filter(EOSSTT %in% "COMPLETED") |> 
  mutate(DCSREAS = "") |>
  count(TRT01A, EOSSTT, DCSREAS)

part_discontinued <- adsl |> 
  filter(EOSSTT %in% "DISCONTINUED") |> 
  count(TRT01A, EOSSTT, DCSREAS)

part_death <- cadsl |> 
  filter(EOSSTT %in% "DISCONTINUED", DCSREAS %in% "DEATH") |> 
  count(TRT01A, EOSSTT, DTHCAUS) |> 
  mutate(EOSSTT = forcats::fct_expand(EOSSTT, "Death Cause"),
         EOSSTT = "Death Cause",
         DTHCAUS = tools::toTitleCase(tolower(DTHCAUS))
         ) |> 
  rename(DCSREAS = DTHCAUS)

dat <- bind_rows(
  part_completed, 
  part_discontinued, 
  part_death) |> 
  inner_join(part_header, by = "TRT01A") |> 
  mutate(percent = n / n_part, n_part = NULL)

# Now the flextable creation with help of `tabulator()`. 

tab <- tabulator(
  dat,
  rows = c("EOSSTT", "DCSREAS"),
  columns = "TRT01A",
  `content_cell` = as_paragraph(fmt_n_percent(n, percent))
)
ft <- as_flextable(tab, spread_first_col = TRUE, 
                   columns_alignment = "right" )

TRT_COUNTS <- setNames(part_header$n_part, part_header$TRT01A)
for (TRT_COD in names(TRT_COUNTS)) {
  ft <- append_chunks(x = ft, part = "header", i = 1,
                      j = tabulator_colnames(tab, columns = "content_cell", TRT01A %in% !!TRT_COD),
                      as_chunk(TRT_COUNTS[TRT_COD], formatter = function(n) sprintf("\n(N=%.0f)", n)))
}

ft <- ft |> 
  labelizor(
    labels = c(labels, DCSREAS = "", ANY = "Number of patients", 
               COMPLETED = "Completed", DISCONTINUED = "Discontinued"), 
    j = "DCSREAS", part = "all") |> 
  align(i = ~!is.na(EOSSTT) | seq_along(EOSSTT) == 1, j = 1, align = "left") |> 
  prepend_chunks(i = ~is.na(EOSSTT), j = "DCSREAS", as_chunk("\t")) |> 
  autofit()
ft
```

### tables

```{r}
resetSession()
adsl <- cadsl

# Change the labels to title case

levels(adsl$EOSSTT)  <- tools::toTitleCase(tolower(levels(adsl$EOSSTT)))
levels(adsl$DCSREAS) <- tools::toTitleCase(tolower(levels(adsl$DCSREAS)))
levels(adsl$DTHCAUS) <- tools::toTitleCase(tolower(levels(adsl$DTHCAUS)))

library(tables)

subject_counts <- table(adsl$ARM)

countpercentid <- function(num, ARM) {
  n <- length(unique(num))
  sprintf("%d (%.2f%%)", 
          length(unique(num)), 
          100*n/subject_counts[ARM[1]])
}

count <- function(x) sprintf("(N=%d)", length(x))

heading <- tabular(Heading("")*1*Heading("")*count  ~
             Heading()*TRT01A, data = adsl)

part1 <- tabular( Heading("")*EOSSTT*DropEmpty()*
                    Heading("")*1*
                    Heading()*countpercentid*Arguments(ARM = TRT01A)*
                    Heading()*USUBJID ~
                  Heading()*TRT01A, 
                  data = subset(adsl, EOSSTT != "Discontinued"))

part2 <- tabular( Heading("")*EOSSTT*
                    Heading("")*DCSREAS*DropEmpty()*
                    Heading()*countpercentid*Arguments(ARM = TRT01A)*
                    Heading()*USUBJID ~
                  Heading()*TRT01A, 
                  data = subset(adsl, EOSSTT == "Discontinued" &
                                      DCSREAS != "Death"))

part3 <- tabular( Heading("")*DCSREAS*
                    Heading("")*DTHCAUS*DropEmpty()*
                    Heading()*countpercentid*Arguments(ARM = TRT01A)*
                    Heading()*USUBJID ~
                  Heading()*TRT01A, 
                  data = subset(adsl, EOSSTT == "Discontinued" &
                                      DCSREAS == "Death"))

rbind(heading, part1, part2, part3)
```
