---
output: html_document
editor_options: 
  chunk_output_type: console
---
## Demographic Tables

### rtables

Using `rtables` only:

```{r, comment= NA}
a_demo_num <- function(x) {
    in_rows(n = length(x),
            "Mean (SD)" = rcell(c(mean(x, na.rm = TRUE),
                                  sd(x, na.rm=TRUE)), format = "xx.x (xx.x)"),
            "Median" = median(x,na.rm = TRUE),
            "Min - Max" = rcell(range(x, na.rm = TRUE), format = "xx.x - xx.x"))
}

a_demo_fac <- function(x) {
    in_rows(.list = c(c(n = length(x)), table(x)))
}

lyt <- basic_table() |>
  split_cols_by("ARM") |>
  analyze(c("AGE", "SEX", "COUNTRY"), afun = list(AGE = a_demo_num, SEX = a_demo_fac,
                                                  COUNTRY = a_demo_fac))
 
build_table(lyt, ex_adsl)
```

Using `rtables` and `tern`

```{r, comment=NA}
lyt <- basic_table() |>
  split_cols_by("ARM") |>
  summarize_vars(c("AGE", "SEX", "COUNTRY"))

build_table(lyt, ex_adsl)
```


### gt

```{r, comment= NA}
library(tidyverse)

# We will use ex_adsl but will assign a unit to the Age column

gt_adsl <- ex_adsl
attr(gt_adsl$AGE, "units") <- "Years"

# This is a customized summary function
# It creates numeric and categorical summaries for specified variables, following the rtables exmaple

custom_summary <- function(df, group_var, sum_var){
  group_var <- rlang::ensym(group_var)
  sum_var <- rlang::ensym(sum_var)
  
  is_categorical <- is.character(eval(expr(`$`(df, !!sum_var)))) | is.factor(eval(expr(`$`(df, !!sum_var)))) 
  
  if (is_categorical){
    df <- df %>% 
      dplyr::group_by(!!group_var) %>% 
      dplyr::mutate(N = n()) %>% 
      dplyr::ungroup() %>% 
      dplyr::group_by(!!group_var, !!sum_var) %>% 
      dplyr::summarize(val = n(),
                       sd = 100*n()/mean(N)) %>% 
      dplyr::ungroup() %>% 
      tidyr::pivot_wider(id_cols = !!sum_var, names_from = !!group_var, values_from = c(val, sd)) %>% 
      dplyr::rename(label = !!sum_var) %>% 
      dplyr::mutate(isnum = FALSE,
                    across(where(is.numeric), ~ifelse(is.na(.), 0, .))) 
    
    sum_unit <- ", n (%)"
    
  } else {
    
    sum_unit <- sprintf(" (%s)", attr(eval(expr(`$`(df, !!sum_var))), "units"))
    
    df <- df %>% 
      dplyr::group_by(!!group_var) %>% 
      dplyr::summarize(n = sum(!is.na(!!sum_var)),
                       mean = mean(!!sum_var, na.rm = TRUE),
                       sd = sd(!!sum_var, na.rm = TRUE),
                       median = median(!!sum_var, na.rm = TRUE),
                       min = min(!!sum_var, na.rm = TRUE),
                       max = max(!!sum_var, na.rm = TRUE),
                       min_max = NA) %>% 
      dplyr::ungroup() %>% 
      tidyr::pivot_longer(cols = c(n, mean, median, min_max), names_to = "label", values_to = "val") %>% 
      dplyr::mutate(sd = ifelse(label == "mean", sd, NA),
                max = ifelse(label == "min_max", max, NA),
                min = ifelse(label == "min_max", min, NA),
                label = dplyr::recode(label, "mean" = "Mean (SD)", "min_max" = "Min - Max", "median" = "Median")) %>% 
      tidyr::pivot_wider(id_cols = label, names_from = !!group_var, values_from = c(val, sd, min, max)) %>% 
      dplyr::mutate(isnum = TRUE)
    
  }
  
  df %>% 
    dplyr::mutate(category = paste0(stringr::str_to_title(deparse(substitute(!!sum_var))),
                                     sum_unit)) 
}

# Perform aggregation for variables Age, Sex and Country

adsl_summary <- purrr::map_df(.x = vars(AGE, SEX, COUNTRY),
                             .f = ~custom_summary(df = gt_adsl, group_var = ARM, sum_var = !!.x)) 

# Count number of patients per Arm

total_n_arm <- ex_adsl %>% 
  dplyr::group_by(ARM) %>% 
  dplyr::summarise(N = n()) %>% 
  dplyr::ungroup() 

# gt

gt(adsl_summary, 
   rowname_col = "label",
   groupname_col = "category") %>%
  tab_header(
    title = "x.x: Study Subject Data",
    subtitle = html("x.x.x: Demographic Characteristics<br>Table x.x.x.x: Demographic Characteristics - Full Analysis Set"),
    preheader = c("Protocol: XXXXX", "Cutoff date: DDMMYYYY")
  ) %>% 
  tab_source_note("Source: ADSL DDMMYYYY hh:mm; Listing x.xx; SDTM package: DDMMYYYY") %>% 
  opt_align_table_header(align = "left") %>% 
  fmt_integer(columns = starts_with(c("val", "min", "max")), rows = label != "Mean (SD)") %>% 
  fmt_number(columns = starts_with(c("val", "sd")), rows = label == "Mean (SD)", decimals = 1) %>% 
  fmt_number(columns = starts_with("sd"), rows = isnum == FALSE, decimals = 1) %>% 
  sub_missing(missing_text = "") %>% 
  summary_rows(groups = c("Sex, n (%)", "Country, n (%)"),
               columns = starts_with("val"),
               fns = list(n = ~sum(.)),
               missing_text = "",
               formatter = fmt_integer) %>% 
  cols_merge_n_pct(col_n = "val_A: Drug X", col_pct = "sd_A: Drug X") %>% 
  cols_merge_n_pct(col_n = "val_B: Placebo", col_pct = "sd_B: Placebo") %>% 
  cols_merge_n_pct(col_n = "val_C: Combination", col_pct = "sd_C: Combination") %>% 
  cols_merge_range(col_begin = "min_A: Drug X", col_end = "max_A: Drug X", sep = " - ") %>% 
  cols_merge_range(col_begin = "min_B: Placebo", col_end = "max_B: Placebo", sep = " - ") %>% 
  cols_merge_range(col_begin = "min_C: Combination", col_end = "max_C: Combination", sep = " - ") %>% 
  cols_merge(columns = c("val_A: Drug X", "min_A: Drug X"), pattern = "{1}{2}") %>% 
  cols_merge(columns = c("val_B: Placebo", "min_B: Placebo"), pattern = "{1}{2}") %>% 
  cols_merge(columns = c("val_C: Combination", "min_C: Combination"), pattern = "{1}{2}") %>% 
  cols_hide(columns = isnum) %>% 
  cols_align(align = c("center"),
             columns = c("val_A: Drug X", "val_B: Placebo", "val_C: Combination")) %>% 
  cols_align(align = "center",
             columns = 1) %>% 
  cols_label("val_A: Drug X" = html(sprintf("A: Drug X<br> N=%i (100%%)", total_n_arm$N[1])),
             "val_B: Placebo" = html(sprintf("B: Placebo<br> N=%i (100%%)", total_n_arm$N[2])),
             "val_C: Combination" = html(sprintf("C: Combination<br> N=%i (100%%)", total_n_arm$N[3]))) %>% 
  tab_options(
    table.font.size = 9,
    page.orientation = "landscape",
    page.numbering = TRUE,
    page.header.use_tbl_headings = TRUE,
    page.footer.use_tbl_notes = TRUE)
```

