on:
  pull_request:
    branches:
      - main

name: pr-run-ok

jobs:
  bookdown:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'buildskip')"
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - uses: actions/checkout@v2

      - name: Google fonts
        run: |
          mkdir -p /usr/share/fonts/truetype/google-fonts
          find tables-book/static/fonts/ -name "*.ttf" -exec install -m644 {} /usr/share/fonts/truetype/google-fonts/ \; || return 1
          fc-cache -f
        shell: bash

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2
        env:
          # install full prebuilt version
          TINYTEX_INSTALLER: TinyTeX

      - name: Add some R options for later steps
        run: |
          cat("\noptions(tinytex.verbose = TRUE)\n", file = "~/.Rprofile", append = TRUE)
          cat(readLines("~/.Rprofile"), sep = "\n")
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: install github packages
        run: |
          install.packages("remotes")
          remotes::install_github("insightsengineering/random.cdisc.data")
          remotes::install_github("insightsengineering/scda")
          remotes::install_github("insightsengineering/nestcolor")
          remotes::install_github("insightsengineering/formatters")
          remotes::install_github("Roche/rtables")
          remotes::install_github("insightsengineering/tern", ref = "v0.7.10")
          remotes::install_github("ardata-fr/doconv")
          remotes::install_github("davidgohel/flextable")
          remotes::install_github("dmurdoch/tables")
          remotes::install_github("pharmaverse/tidytlg")
        shell: Rscript {0}

      - name: Pandoc and Tinytex info
        run: |
          rmarkdown::find_pandoc()
          tinytex::tlmgr("--version")
          tinytex::tl_pkgs()
        shell: Rscript {0}

      - name: render book
        run: |
          setwd('tables-book')
          rmarkdown::render_site(encoding = 'UTF-8')
        shell: Rscript {0}
